### ISSUE TITLE
Artur Holiev Lab #3

### ISSUE THREAD

**Issue by holiev** [VladStorozhenko/se-labs-cs221be#17]
# We should:
![image](https://user-images.githubusercontent.com/92891111/139129986-a1f8d595-8e22-4442-8801-09c27195ef3c.png)

- [x]  _Creating of SRS (Software Requirment Specification)_ #42 
- [x] _Create Activity and Use case diagrams_ #19 
- [x] _Create cpp file_ #20
- [x] _Write appropriate modified code according to my task's number_ #21 
- [x] _Testing_ #59
